# Generated by Django 5.1 on 2024-10-19 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_atividade_sentimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(blank=True, max_length=255, null=True)),
                ('intensidade', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('medicamento', models.CharField(blank=True, max_length=255, null=True)),
                ('medico', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
