# Generated by Django 5.1 on 2024-10-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_registrosaude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_dormidas', models.IntegerField()),
                ('qualidade_sono', models.IntegerField()),
                ('meta_sono', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
