# Generated by Django 5.1 on 2024-10-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sono_user_alter_registrosaude_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencias', models.TextField()),
                ('restricoes', models.TextField()),
                ('objetivos', models.CharField(max_length=50)),
            ],
        ),
    ]
